### ISSUE TITLE
Long paths in content cause tfs / build server errors

### ISSUE THREAD

**Issue by markwemekamp** [KevinJump/uSync3.0#118]
Hi Kevin,
We're using usync content edition at the moment for a webportal we're building. We have some initial content we want to add to the the portal when we first deploy it.

We are experiencing some problems with filepaths that are too long (> 259 characters), this is because of the way content is saved in directories with the same name as the umbraco nodes.
Is there a way (perhaps a setting) to work around this problem?

Kind regards

**Comment by KevinJump** [comment]
hi, 

you should be able to add a setting to the content and media handlers to use short names. 

adding `<UseShortIdNames>true</UseShortIdNames>` to usyncbackoffice.config and running and export, should see the files/folders inside the media/and config sections use ids instead of names, and hopefully this results in shorter paths.

**Comment by markwemekamp** [comment]
Hi,
Thank you for the fast response (as always :) ).
I've added the setting and it appears ContentHandler doesn't implement this feature (yet). uSyncBaseHandler does this in the GetItemFileName method but ContentHandler inherits from BaseContentHandler which does not have this functionality.

Also it would be really nice to have the length of the short guid configurable. 22 characters is still pretty large, since in our case some of the node structures are up to 7 levels deep.

If you'd like some help implementing these features, I can help

**Comment by KevinJump** [comment]
Urgg :( I should impliment it ! 

I need to check because the call base.GetItemFileName in the BaseContentHandler for content does do the short name thing but obvs not right. :( 

More than happy for you to have a look at why it's not working.

The issue with the ID is it needs to be unique but also the same on multiple installs of umbraco, so a way of getting from guid to something unique but shorter is the challenge. 

Kevin

**Comment by KevinJump** [comment]
I meant **it** should do it no I ! didn't want to sound all protective there !

**Comment by markwemekamp** [comment]
Haha, cool I'll give it a look then ;)

**Comment by KevinJump** [comment]
change for #130 should also resolve this - it will be in the next release (3.3.3) due this week. (27th April)
