### ISSUE TITLE
Import / Full Import introduces additional nodes

### ISSUE THREAD

**Issue by james-speller** [KevinJump/uSync3.0#120]
Hi got a strange issue for you

After I do a full export and then either a full import or import I get issues with additional nodes.

Sometimes these show up in my tree in the form:

mynode
mynode (1)

Other times they don't appear in the tree, but cause a problem when attempting to publish the correct node. When this occurs I see the message 'This document is published but its url would collide with content'. 

This mainly happens when we do an export from a feature branch, merge it into the release and then on the release branch do an import/full import. It happens locally on both developer machines, and on our test server.

Any ideas why it's occurring, or is there any information I can provide to help work out what's going wrong?

**Comment by KevinJump** [comment]
Hi

if you are using the latest version of usync (because there was an issue with this pre 3.3.1 i think) then it's probably mis-matched guids ? the import of content will attempt to find a node based on the key (guid) and it also looks for the contents parent by guid. 

If it doesn't match by guid usync will attempt to find the content by alias and content type. so if the name and content type are the same you shouldn't get a duplicate - but that does depend on uSync at least finding the parent node.

**Comment by james-speller** [comment]
We're using 3.3.0.740 I'll get the latest version and see how that goes. Thanks for the reply
