### ISSUE TITLE
Problem with start node in Mediapicker

### ISSUE THREAD

**Issue by markwemekamp** [KevinJump/uSync3.0#132]
Hi Kevin,
I currently have a problem with setting the start node of a mediapicker. I don't know if this is by design, but it appears the node id is being used instead of the node key, which is causing trouble on our staging environment. The start node is empty after I run an import

![Report](http://i.imgur.com/PYJsq5s.png)

The xml output
```xml
<DataType Name="External file picker" Key="3c2aeb0b-b490-4090-afea-b6bbe4f1fd54" Id="Umbraco.MultipleMediaPicker" DatabaseType="Nvarchar">
  <Nodes>
    <Node Id="1393" Value="Global\Shared\KnowledgeBase\External" Type="media" MapGuid="1" />
  </Nodes>
  <PreValues>
    <PreValue Id="123" Value="1" Alias="multiPicker" />
    <PreValue Id="124" Value="" Alias="onlyImages" />
    <PreValue Id="125" Value="1" Alias="disableFolderSelect" />
    <PreValue Id="126" Value="1393" Alias="startNodeId" MapGuid="1" />
  </PreValues>
</DataType>
```

I'm using usync version: (uSync.BackOffice 3.3.1.740) (uSync.Core 5.6.1.740) [uSync.Content: 3.2.2.740]

Is this a bug, a feature of maybe already fixed in a newer version of usync?

**Comment by KevinJump** [comment]
Hi, 

this is partly by design - 

what uSync does on import attempt to find the ID based on the path in the Node Id value. 
(so the MapGuid values are used to match the prevalue with the path ( so if there was more than one value to map you would see multiple node values)

on import usync walks the media tree, using the path (so it looks for global, then shared, then knowlagebase, etc... 

if at any point it can't find an element in the path, it will exit and not change the value.

this can be a bit of a pain because it then imports the value as is (so 1393) not what it might be - i have been looking and thinking about this behaviour recently and I think it should in theory just not set the value at all if the mapping fails. 

but if you have that structure in your media folders then it 'should' work

**Comment by markwemekamp** [comment]
I have set up this structure in my media section, but the start node is empty after an import

![Media](http://i.imgur.com/FYtEGLI.png)

Do I have to do additional configuration or should this work out of the box?

**Comment by markwemekamp** [comment]
I've taken a look at `DataTypeSerializer` but it doesn't look like the "Nodes" node is used there. The prevalues of the "Prevalues" are directly copied to the datatype in the `DeserializeUpdatePreValues` method.

Am I looking at the wrong place or has the functionality you described above disappeared from the code base?

**Comment by KevinJump** [comment]
Hi 

it starts here as part of DeserializeGetMappedValues https://github.com/KevinJump/uSync/blob/Dev-v7_4/Jumoo.uSync.Core/Serializers/DataTypeSerializer.cs#L191 

which is the called at the top of DeserializeItem https://github.com/KevinJump/uSync/blob/a08421b19c53ed5a34b7fdab035f1c2e187e09df/Jumoo.uSync.Core/Serializers/DataTypeSerializer.cs#L52

that does all the mapping of MapGUid values. the LoadMapper function should go off and get a uSyncValueMapper based on the settings in the usynccore.config https://github.com/KevinJump/uSync/blob/a08421b19c53ed5a34b7fdab035f1c2e187e09df/Jumoo.uSync.Core/Serializers/DataTypeSerializer.cs#L479

ultimately the mapper is what put s the MapGuid value in - so it should be getting found but for media you should end up at the ContentIdMapper (it does both) https://github.com/KevinJump/uSync/blob/a08421b19c53ed5a34b7fdab035f1c2e187e09df/Jumoo.uSync.Core/Mappers/ContentIdMapping.cs#L53

and this takes the guid and goes and finds the local ID to put in it's place. 

Thats the theory anyway 😄 - but i suspect something small and stupid is wrong in the change, It's just going to take a little time to work out what it is and where.

**Comment by KevinJump** [comment]
Hi,

I've had a look and i think there is a bit of a logic change needed, in how the process falls back. 

At the moment when a mapping fails (so we can't find the target node) we use the default value in the xml which isn't necessarily the same as the default value in the install. 

At the moment the mapping is done independently of the existing node, so there needs to be a change where the existing node is also loaded so we can pluck default values out of the existing node if the mapping fails. so it's a bit of a rewrite of the MapperHelper.

Of course in 7.6 the new pickers make this whole problem just dissapear* but we need to do the mappings for non 7.6 and non content synced installs

*the 7.6 pickers store GUIDs of the content you might be pointing to, but this is only useful if you also sync the content because if you don't sync the content then the guids won't be there to match,

**Comment by KevinJump** [comment]
Will need testing - but the mapper is written a bit diffrently now, to do two things:
1. actually map - because it wasn't doing that properly.
2. not overwrite the value inside umbraco if it can't map. this means if you have set it manually in umbraco, a usync import won't break it.
