### ISSUE TITLE
Exception 'Illegal characters in path' with uSyncMediaFileMover and Umbraco 7.6.*

### ISSUE THREAD

**Issue by ivo-centric** [KevinJump/uSync3.0#134]
Hi Kevin,
Just updated to Umbraco version 7.6.1 (from 7.5.11). We are using the uSync ContentEdition to sync the Media. With the new Umbraco version the moving of media files crashes in `uSyncMediaFileMover.ImportFileValue`. The new Umbraco version has a new implementation of `ContentExtensions.SetValue(this IContentBase content, string propertyTypeAlias, string filename, Stream filestream)` and it seems that it handles the given uSync media item incorrectly instead of getting the src to the file it receives the crop Json (I think). Do you have an idea how to fix/workaround this?
Thanks,
Ivo

**Comment by KevinJump** [comment]
Hi, I am not sure to be honest - i will have to have a dig around. 

one work around might be to not have uSync copy the actual media ? **(but i would test this a lot before going live on an existing site!)**

you can have usync set the media config, but then assume the media is already in place. so post about 7.3 the /media/[foldernumber]/ isn't in the db anymore, when umbraco starts up it just gets the highest value from disk. 

so you can "just" copy the media folder between installs, and have uSync just do the config (so then i don't think it will do the stream stuff) 

in usynccore.config 
```
  <MoveMedia>false</MoveMedia>
```

I am not sure this will work for you as it might not be ideal for an existing install setup (you're ids are likely different between your installs) but its what i would recommend if you where starting fresh

**Comment by ivo-centric** [comment]
Thanks, your suggested workaround works for us. We now put all the files in the Umbraco /media folder in sourcecontrol and use the `<MoveMedia>false</MoveMedia>` setting so that it does not copy files from uSync to the media folder and 'bypasses' the exception. (We are developing an Umbraco website with a team and every developer has its own local database and we are using uSync to sync the settings and content.)

**Comment by aDotNetDeveloper** [comment]
Hi Kevin,

have migrated from 7.5.11 -> 7.6.3

have always moved media in previous version
`<MoveMedia>true</MoveMedia>`

re-exported with uSync 5.6.4.740

on import of Media into new umbraco instance i get this
```
 2017-07-05 16:20:04,011 [P9916/D2/T7] DEBUG Jumoo.uSync.Core.Helpers.uSyncMediaFileMover - 
--------------------- FILE MOVE ---------------
 2017-07-05 16:20:04,013 [P9916/D2/T7] ERROR Umbraco.Core.Media.UploadAutoFillProperties - Could not populate upload auto-fill properties for file "1001/logo.png".
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Development\MediaCMS\media\1001\logo.png'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Umbraco.Core.IO.PhysicalFileSystem.OpenFile(String path)
   at Umbraco.Core.IO.ShadowWrapper.OpenFile(String path)
   at Umbraco.Core.Media.UploadAutoFillProperties.Populate(IContentBase content, IImagingAutoFillUploadField autoFillConfig, String filepath)
 2017-07-05 16:20:04,137 [P9916/D2/T7] DEBUG Jumoo.uSync.Core.Helpers.uSyncMediaFileMover - 
--------------------- FILE MOVE ---------------
```

regards
Wayne

**Comment by auniqueusername** [comment]
I have also run into this issue after upgrading to:
- Umbrao 7.6.4 
- uSync 3.3.4.740 
- uSync.BackOffice 3.1.5.740 
- uSync.ContentEdition 3.3.3.740 
- uSync.ContentMappers 3.3.3.740 
- uSync.Core 5.6.4.740 

The error occurs with `<MoveMedia>true</MoveMedia>` when importing an Umbraco.ImageCropper media item to a clean Umbraco instance.

I cloned the Umbraco and uSync codebases and traced the execution to find the error. @ivo-centric is correct that the exception message is due to ImageCropper JSON being treated as a file path.

In my case when _Jumoo.uSync.Core.Helpers.uSyncMediaFileMover.ImportFileValue_ [line 109](https://github.com/KevinJump/uSync/blob/5.6.4/3.3.4/Jumoo.uSync.Core/Helpers/uSyncMediaFileMover.cs#L109) calls `item.SetValue("umbracoFile", ..., ...)` then _Umbraco.Core.IO.MediaFileSystem.StoreFile_ [line 229](https://github.com/umbraco/Umbraco-CMS/blob/release-7.6.4/src/Umbraco.Core/IO/MediaFileSystem.cs#L229)  will try to delete the file indicated by the old value of the _umbracoFile_ property which is the ImageCropper JSON deserialized from the XML.

I was able to prevent the error by modifying _uSyncMediaFileMover_ so that it explicitly set the _umbracoFile_ property to null before calling `item.SetValue`. This ensures the _MediaFileSystem_ will not try to treat the value as a path.

**uSyncMediaFileMover.cs:107**

     using (FileStream s = new FileStream(file, FileMode.Open))
     { 
          // Set the umbracoFile value to null, so that when SetValue is called 
          // the 'old' value will be null and Umbraco will not try to delete the file
          item.Properties["umbracoFile"].Value = null;

          item.SetValue("umbracoFile", Path.GetFileName(file), s);
          changes = true;
     }

@KevinJump: I am not familiar enough with uSync to suggest a proper fix, but I hope this helps. If you describe a better solution, I could submit a PR.

**Comment by KevinJump** [comment]
I am going to revisit this in the next patch release.

**Comment by KevinJump** [comment]
Change is in - i am going to do some legacy testing before the next release to check it doesn't break anything else

**Comment by KevinJump** [comment]
in 4.0.5
