### ISSUE TITLE
Image properties not syncing

### ISSUE THREAD

**Issue by rogerogert** [KevinJump/uSync3.0#161]
The properties width, height, type and size from Image files are not synchronized by uSync.

Version tested:
uSync.BackOffice 4.0.0.760
uSync.Core 6.0.0.760
uSync.Content: 4.0.0.760
Umbraco 7.7.4

**Comment by KevinJump** [comment]
Hi 

yeah had a quick play around - the values are set if the media folder has also been copied over at the time of syncing - but if the media is missing then the values are blank - i suspect the umbraco process is blanking them for missing media. 

however - they don't then appear when the media is copied over unless you do a *full import* - this shouldn't require a full import as usync should notice the difference between the values on disk and the ones in umbraco - so that is probably the bug that needs fixing in this situation.

**Comment by KevinJump** [comment]
These changes will enable the import to happen if the values are missing (because media was missing on first pass). It will require the match mode is in Mismatch within the usyncCore.Config file. 

As suspected these values are blanked by umbraco if the file isn't in the media folder when the media item is saved  (so even while uSync is setting these values - umbraco is overriding them with the ones from the image on save) 

If you put the image there and then save the media item it puts the values back - so a quick fix until this is released in the next patch - is save all the media items (yeah a pain, and probably a code thing)

**Comment by rogerogert** [comment]
Hi Kevin. Thanks for your detailed response. I ran the full import and the attributes were synced as expected. Thanks for the feedback.

**Comment by KevinJump** [comment]
this will be in the next release (just wrapping it up now)
