### ISSUE TITLE
usync - radiobuttonlist - sortorder issue

### ISSUE THREAD

**Issue by ocastele** [KevinJump/uSync3.0#176]
Situation:
1) on development umbraco (7.10.4): 
usync 4.0.5 installed (Sync Source checked)
Created a doc type (FAQ) with a radiobuttonlist with 5 values in it (a,b,c,d,e)

2) on live umbraco (7.10.4):
usync 4.0.5  installed (Sync Target checked)
Synced (so doc type FAQ is created)
Created a FAQ , marked "a" in the radiobutton list

3) on dev umbraco:
Change sortorder in de radiobuttnlist (e,a,b,c,d)

4) on live umbraco
Synced
=> option "e" is marked in the FAQ document.

Problem: option "a" should still be marked.

**Comment by KevinJump** [comment]
Hi

yeah i am looking at this - at the basic level we are using the CORE api endpoints for updating these lists, and there is even stuff in the comments inside the umbraco core about these types of issues. 

Its something i am hopefully going to have a play about with to see if we can improve the way it's handled. its all to do with how you track before and after really.

**Comment by KevinJump** [comment]
Lists are a pain! 🤕 - but this update might help. 

The internal Umbraco API calls take the list of prevalues you have as an Alias and Value combo - but the content attaches to the ID (totally internally this - because if you ask for the value you don't get the ID even at a IContent level you get the alias or the value)

So when you sort (or insert something into) a list the internal IDs are maintained but the aliases values all shuffle into the new order - uSync matches of the Alias, and this causes it to get lost a bit on lists in that the matching alias, is no longer for the same item - so we update the name of an existing item to the item that is now in its place - sadness (and github issues) ensue. 

so this update - for list datatypes (dropdowns, checkboxes, radios) will first try to match the prevalue based on the actual value - and if that fails the alias. so sorting (or adding new items) to a list should now work because we find the right internal prevalue and update it (and it's alias) 

**This will not always work however - if you rename an item in the list and change the sort order of the list in one change - then we are a bit lost :( we have no permanent key between prevalues in one system and prevalues in another to be able to track whats happened, all we can do is best guess and in this case that will fail :(**

**Comment by KevinJump** [comment]
updating the uSync.Core files to version 6.0.6 should resolve this issue. 

```
install-package uSync.Core
```

_or download the uSync.Core.zip from [the release](https://github.com/KevinJump/uSync/releases/tag/6.0.6-Core) and copy Jumoo.uSync.Core.dll into the site bin folder_
