### ISSUE TITLE
Document Type Collection with a Master

### ISSUE THREAD

**Issue by JasonElkin** [KevinJump/uSync3.0#208]
uSync ignores the master when new documents are created as a Document Type Collection.

Using the new Document Type Collection option in Umbraco 7.13.1 causes the master document type to be ignored.

Steps to replicate:
Create a folder called "Folder" and inside it a doctype called "MasterDocType"
Right-Clink on MasterDocType -> Create -> Document Type Collection
Create Parent Document Type called "Parent" and Item Document Type called "Child".

Expected behaviour:

- def.config files are created at `~/uSync/DocumentType/Folder/masterDocType/parent/` and `~/uSync/DocumentType/Folder/masterDocType/child/`
- def.config file for both document types contains the relevant `<Master Key="...guid...">masterDocType</Master>`  and  `<Composition Key="...guid...">masterDocType</Composition>` nodes.

Actual behaviour:
- def.config files are created at `~/uSync/DocumentType/Folder/masterDocType/parent/` and `~/uSync/DocumentType/Folder/masterDocType/child/`
- Neither the master nor composition nodes appear in the def.config file.

**Comment by KevinJump** [comment]
Doctype Collections, don't create documents under a master the way the rest of Umbraco does and i can't say that won't have knock-on effects anywhere.

With the advent of compositions when Umbraco creates a child doctype, it also creates the composition which is why you see the Composition entry for the master in the uSync file. 

but creating them with the DocType Collection option doesn't do this, it sets the parent Id of the document, but it doesn't also set the composition  - as we were expecting the composition too, uSync didn't then write out the master.

the fix does a second check, (before the folder check) to see if the document should have a parent.

**Comment by KevinJump** [comment]
Further testing, (fixed usync for this) this is a bug in Umbraco (will raise isseue) becuase it means the items created by collections don't inherit the master properties properly (well they certainly don't show them in the editor). 

this is because the master is not in the composition collection

**Comment by KevinJump** [comment]
Umbraco Bug Report : https://github.com/umbraco/Umbraco-CMS/issues/4473

**Comment by KevinJump** [comment]
We are not going to fix already broken document type collections in uSync - because while this might well be desirable it might cause unintended consequences for people 

if you have already built your site, and then all of a sudden uSync fixes this, you doctypes would end up with loads of new properties (that might even clash). 

uSync will continue to mirror the Umbraco instance- even if that instance is broken.

**Comment by KevinJump** [comment]
"Fixed" in 4.0.10
