### ISSUE TITLE
Child document types are not serialized.

### ISSUE THREAD

**Issue by JimBobSquarePants** [KevinJump/uSync3.0#35]
Hola

Umbraco 7.4.1
uSync 3.1.0.740

Adding additional child document types through the permissions section in the doctype editor does not persist the updated collection to the config files.

No errors that I can see are logged. If you need more info let me know and I'll dig around.

**Comment by KevinJump** [comment]
yeah 

this issue is fixed https://github.com/KevinJump/uSync/issues/33 but i just haven't had the time to test the release and push it out :disappointed: 

if you [grab the dlls, from the last check in](https://github.com/KevinJump/uSync/tree/Dev-v7_4/umbPackage/uSync.BackOffice) they contain the fix, but i will try to squeeze the release out this week.

**Comment by KevinJump** [comment]
fixed in latest release (3.1.2 / 5.3.3) of usync and usync.core

**Comment by JimBobSquarePants** [comment]
Ah excellent. Thank you!
