### ISSUE TITLE
Issue with usync snapshots

### ISSUE THREAD

**Issue by victorcea87** [KevinJump/uSync3.0#36]
Hi,

I have added the snapshots package to my visual studio solution but when I deploy I can see these errors:

![image](https://cloud.githubusercontent.com/assets/2836729/14277519/be85128a-fb23-11e5-8755-d2a73e5a89ba.png)

And the snapshots are not working.

Any ideas why?

**Comment by KevinJump** [comment]
Hi 

did you add the package (via our.umbraco) or nuget ? 

does you're deployed solution include the dlls ? (snapshots is in Jumoo.uSync.Snapshots.dll)

**Comment by victorcea87** [comment]
Via nuget and yes, the solution include the dlls, I can see the snapshots dll

**Comment by KevinJump** [comment]
Hummm :confused: 

i don't think it would need rebuilding / restarting as putting the dll there does that, but you only get a 404 from the URLs when umbraco can't find the controllers and the controllers are in that dll :disappointed: 

do you have any more info either from the Chrome dev console or what happens if you put those URLs directly into your browser (so http://site/umbraco/backoffice.....)

**Comment by victorcea87** [comment]
Just a second...I don't see that dll in the bin folder of the website...

**Comment by victorcea87** [comment]
Sorry, issue with the solution, the dll was not referenced in the csproj file :(
