### ISSUE TITLE
Grid Mapper

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync3.0#44]
Currently content doesn't get mapped if it's inside a grid, 

you can just throw the standard mapper at a grid and it will most likely work, but to be sure we should build a grid mapper

**Comment by KevinJump** [comment]
this is similar to nested and archetype accept the grid can in theory have loads of other type stuff in it.

in the first pass - i am putting in the mapping for the core grid stuff so that's anything that has an alias of rte or media in the gird.editors.config. as they just map a value and id. 

longer term we could push this out into a config (in usync.core.config) but we are getting quite niche

**Comment by madsoulswe** [comment]
Maybe default the grid-control-mapper should look for a "grid.{alias}"-mapper, so that you can make a custom mapper for ever grid-controller.

`<uSyncContentMapping Alias="Grid.{ALIAS}" Mapping="CUSTOM" CustomMappingType="{NAME}"/>`

In that way you wouldn't need a switch to check for mappers? =)

Example om types that I would want to convert:
https://our.umbraco.org/projects/backoffice-extensions/doc-type-grid-editor/
https://our.umbraco.org/projects/backoffice-extensions/leblender/

**Comment by KevinJump** [comment]
that is a very good idea :100: makes it way easier.

**Comment by KevinJump** [comment]
Still haven't fully tested this, (i.e not tested it)

I want to keep it backwards compatible, but also grid mappers need more settings - so i've added an settings property to the mapper config .

for grid mappers, it just points to the value that is mapped inside the `control` json of that grid element. most grid elements either have the ids in value or id (as in media). so i think this will cover them, I was going to make the settings property a json string, but it's open to be used in what ever format is needed by the mapper. for now we just need the value we want.

Will test this properly when i get an opertunity, but i think this is the right concept

**Comment by KevinJump** [comment]
tested and this is now, will be in next release
