### ISSUE TITLE
More Control Over Handlers

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync3.0#59]
Better Control over how handlers behave on a import / export 

I know some people have a create only directory handler, so it would be nice to be able to do that type of thing via the config.

Just while i am working this out any comments are welcome. 
- IsNew - to serializers to allow create only option
- ability to have named handler groups ? so you could call the import programmatically with a handler group, or even a set of handlers, this would let things like snapshots have their own handler settings.

**Comment by lucasch** [comment]
I can outline a bit of how we're programmatically using the handlers, but it might be too specific to our case.

We use a combination of a custom controller (that serves as a proxy for uSync and any of our custom migration) and command line tool to do our automated deployments and patching (we have ~175 sites).  The command line tool has an XML spec file that specifies which usync operations to perform an when, here's an example:

> ```
> <Op Api="Sync" Name="Perform" Types="DataType,Template,ContentType,MediaType,Language,Dictionary,Macro" />
> <Op Api="Sync" Name="Perform" Types="Content,Media" CreateOnly="True"/>
> ```

The Perform action parses the Types and enables the listed handlers, disabling all others.  Then a call to ImportAll performs the required uSync stuff we need.  The CreateOnly flag denotes that sync operation should only fire when we create a new site, otherwise they're run on creation and patching.  I can see handler groups being handy here.

We do have a subset of sites that require we don't delete properties that exist in Umbraco but not in the serialized files.  I haven't looked into how to achieve this in uSync 3 yet, it'd be nice to have something like a 'NoRemove' flag that prevents properties from being removed on deserializing.

I'm liking the new architecture of uSync 3, it made this stuff much cleaner on our end, so thanks!

**Comment by KevinJump** [comment]
some new bits of handler logic in the update.

## 1. Handler Groups 

Handlers can now be grouped by the Group="" attribute. 

```
 <Handlers Group="default" EnableMissing="true">
    <HandlerConfig Name="uSync: DataTypeHandler" Enabled="true" />
    <HandlerConfig Name="uSync: TemplateHandler" Enabled="true" />
    <HandlerConfig Name="uSync: ContentTypeHandler" Enabled="true" />
    <HandlerConfig Name="uSync: MediaTypeHandler" Enabled="true" />
    <HandlerConfig Name="uSync: LanguageHandler" Enabled="true" />
    <HandlerConfig Name="uSync: DictionaryHandler" Enabled="true" />
    <HandlerConfig Name="uSync: MacroHandler" Enabled="true" />
    <HandlerConfig Name="uSync: DataTypeMappingHandler" Enabled="true" />
    <HandlerConfig Name="uSync: MemberTypeHandler" Enabled="false" />
  </Handlers>
  <Handlers Group="DataAndDocs" EnableMissing="false"> 
    <HandlerConfig Name="uSync: DataTypeHandler" Enabled="true" />
    <HandlerConfig Name="uSync: ContentTypeHandler" Enabled="true" />
  </Handlers>
```

The default config will still work with this (Group defaults to Default, EnableMissing defaults to true)

it means we can have handler groups inside usync, so calling the Import/Export functions with the second group would only get you DataTypes and ContentTypes imported.

For backwards compatibility the EnableMissing has to default to true (so an existing uSync Import will import from handlers even if they are missing from the config). 

## 2. Handler Actions

Handlers can now be turned of by action

`<HandlerConfig Name="handler" Enabled="true" Actions="All,Import,Export,Events" />`

(default is All), this value is checked as part of a call to Import/Export and SetupEvents, so if a handler's actions are "Import" it won't run any export or trigger files on any Saves inside Umbraco. 

## 3. Handler Settings

this was in the latest update but any settings underneath a handler 

```
<HandlerConfig Name="myHandler" Enabled="true">
  <Setting Key="MySetting" Value="MyValue" />
</HandlerConfig>
```

will get passed to the Handler's `LoadHandlerConfig` function if it implements `ISyncHandlerConfig` this means we can in theory start to have handlers that accept their own settings in a way that doesn't blow the config up in the future. 

Opening up the possiblity of have things like non-destructive handlers as part of the core back office things.

_this all needs a bit of testing, but will probably be in the next release (and will almost certainly trigger a minor version bump to 3.2)_

**Comment by lucasch** [comment]
This looks great!  I hope I can get some time to test this out this week as the non-destructive stuff will be a great help.  I had previously hacked in a stop-gap solution for us but planned to revisit.

**Comment by KevinJump** [comment]
this is working nicely for the latest builds, nothing in the core really takes advantage of it (BackOffice using the Default group with EnableMissing=true), but once it's in there it can be used. 

Will be in next release.
