### ISSUE TITLE
Add uSync Folder to list of folders when deploying

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync3.0#69]
the umbraco package has a nifty trick of including the umbraco & umbraco_files folders as part of the solution when you deploy. Even though they aren't in your visual studio solution.

this is done though the use of a umbraco.targets and umbraco.props file that are put into the solution when you install it via nuget. 

we should add these settings for uSync so the usync folder is deployed too.

**Comment by dinc5150** [comment]
Hey Kevin,

All of a sudden I've been having issues with deploying my sites. All of a sudden it's deploying the whole uSync folder (where it had not originally). Thought it was something that I was doing until I saw this enhancement. 

I develop locally and I selectively push snapshots up to the staging or live site, which had worked great, however I'm also now getting the uSync data being overridden on the server which I don't want to alter. I like having the usync/data/ folder as an additional file backup of the site.

Do you know of any ways that I can disable the uSync target file so that it's not automatically pushed up on my projects? 

Thanks

**Comment by KevinJump** [comment]
Hi 

I think (although i need to google a bit) you can add your own [exclude your own files from deployment,](https://www.asp.net/web-forms/overview/deployment/advanced-enterprise-web-deployment/excluding-files-and-folders-from-deployment) and they will override the targeted ones (or remove the uSync.targets references from the csjproj file?)

**Comment by dinc5150** [comment]
Thanks Kevin,
I played around with it today. I tried overriding it with a  .wpp.targets file, but it didn't seem to work (Probably me doing something wrong), so I resorted to commenting out the lines in the .csjproj which seems to do the job. Thanks for your help!
